### ISSUE TITLE
Behave of catchAll

### ISSUE THREAD

**Issue by politrons** [scalaz/ioeffect#23]
I´m learning the monad IO of scalaZ and I cannot understand how catchAll and catchSome operators works.
I was expecting so see a behave like the onError or onErrorrResumeNext of RxJava, but instead is not catching the throwable, and it´s just breaking the test and throwing the NullPointerException.

Here my two examples

      @Test
      def catchAllOperator(): Unit = {
        val errorSentence: IO[Throwable, String] =
          IO.point[Throwable, String](null)
            .map(value => value.toUpperCase())
            .catchAll(error => IO.fail(error))
        println(unsafePerformIO(errorSentence))
    
      }

And catchSome example

      @Test
      def catchSomeOperator(): Unit = {
        val errorFunction = new PartialFunction[Throwable /*Entry type*/ , IO[Throwable, String] /*Output type*/ ] {
    
          override def isDefinedAt(x: Throwable): Boolean = x.isInstanceOf[NullPointerException]
    
          override def apply(v1: Throwable): IO[Throwable, String] = IO.point("Default value")
        }
    
        val errorSentence = IO.point[Throwable, String](null)
          .map(value => value.toUpperCase())
          .catchSome(errorFunction)
        println(unsafePerformIO(errorSentence))
    
      }

Any idea what I´m doing wrong?. 

Regards

**Comment by jmcardon** [comment]
```scala
  def catchAllOperator(): Unit = {
    val errorSentence: IO[Throwable, String] =
      IO.point[Throwable, String](null)
        .map(value => value.toUpperCase())
        .catchAll(error => IO.fail(error))
    println(unsafePerformIO(errorSentence))

  }
```

1. We dont use nulls in scala. Anything you think may use a null we wrap in `Maybe` or `Option`.
2. This makes your map, which should be a pure function, completely nonsensical since it can throw an error as `toUpperCase()` is not defined on a null value. `map` doesn't catch exceptions, as it should. This is intended behavior and it's great since it shows immediately you have a programming error.
3. Even if for whatever reason this snippet _did_ catch, it would still fail with a `NullPointerException`, since `catchAll(e => IO.fail(e))` all it does is rethrow the error.

```scala
  @Test
  def catchSomeOperator(): Unit = {
    val errorFunction = new PartialFunction[Throwable /*Entry type*/ , IO[Throwable, String] /*Output type*/ ] {

      override def isDefinedAt(x: Throwable): Boolean = x.isInstanceOf[NullPointerException]

      override def apply(v1: Throwable): IO[Throwable, String] = IO.point("Default value")
    }

    val errorSentence = IO.point[Throwable, String](null)
      .map(value => value.toUpperCase())
      .catchSome(errorFunction)
    println(unsafePerformIO(errorSentence))

  }
```

1. Again, null. Don't use null in scala. Anyone using null in Scala is doing it wrong. We have `Option` or `Maybe` for that.
2. `map` can throw, it won't be caught. As it should. `map` should be for pure functions. If you want to make that unholy snippet pure, which by the way should _never_ happen because you should use maybe anyway, make it `IO.point(blah).flatMap(e => IO.syncThrowable(operationon(e))`. this isn't something `IO` should deal with though, really. `null` isn't side effecting, it just means there is no such value, it's just not represented by the type system. It only becomes unholy when you go outside the scalazzi subset which is the only way to approach scala sanely.
3. For the sake of it, you can make your `errorFunction`:
```scala
val errFun: PartialFunction[Throwable, IO[Throwable, A]] = {
    case e: NullPointerException => IO.now("This shouldn't ever happen")
  }
```

**Comment by politrons** [comment]
Hi,

Thanks for the response. Just to be clear, I never use null in my coding, here I was just trying to force a NullPointerException with the assumption that IO catchAll operator can control that Throwable.
Any idea how can I test then the use of both operators?, If they cannot control Throwables in the Monad, for what for are they used?. 
Regards.

**Comment by politrons** [comment]
I would apply same question for retries operators. They are not able to control any throwable that might happen in the monad, so then, how are they used?. I think it would be great to have some other examples more than just open file that might not exist.

Thanks

**Comment by jmcardon** [comment]
You have to understand that the catching should happen inside an io action. 

What you're showing is a programming error.

Don't expect pure functions to catch errors. This is wrong. 

Like I said, if for whatever unholy reason you need to catch an error like NPE:

```
 @Test
  def catchSomeOperator(): Unit = {
    val errorSentence = IO.point[Throwable, String](null)
      .flatMap(value => IO.syncThrowable(value.toUpperCase()))
      .catchAll(_ => IO.now("lol"))
    println(unsafePerformIO(errorSentence))
  }
```

**Comment by politrons** [comment]
Thanks again, 

I understand that NPE is not the best example since it´s bad praxis, but the documentation of the operator says:

> if you want to catch and recover from all types of errors and effectfully attempt recovery, you can use the catchAll method:

I´m still confuse in which scenarios is appropriate the use of this operator.

**Comment by jmcardon** [comment]
I'm trying to get at the fact that `catchAll` doesn't mean 
```scala
try { YOLO } catch { EVERYTHING } 
```

`catchAll` means "catch all reasonably handled exceptions within your `IO` action". It means, if you wrote your code properly (i.e not throwing in `map`), then `catchAll` means "handle errors thrown sanely". this means actual errors, not programming errors.

What you're expecting is the equivalent of:
```scala
try { myIO} catch { case e: Throwable => IO.fail(e) } 
```

This is a significant different between `cats-effect` IO and scalaz8 IO. Scalaz8 does not catch programming errors in map.  

If you expect to be resilent against bad code, it's not what scalaz8 is tailored for.

**Comment by politrons** [comment]
Sorry, I'm very newby with this library, but when you said 

> "handle errors thrown sanely". this means actual errors, not programming errors.

I normally use Types for errors using Either[Error, Happy_type] as the IO does, and  those control errors as you mentions are just the two effects that my programs has, and I decide to return one type or another, but in any case I never need a handler error operator as catchAll since is one of the effects of my program.

So again, if this operator is only meant to be used as you suggest for business error as a effect, why it's really need it?.

Maybe some coding example if you have 5 minutes to spare?,  it would be amazing.

Regards.

**Comment by emilypi** [comment]
@politrons What @jmcardon is saying is that `catchAll` should be used as a kind of default `catch` for your errors of a certain type defined by you, but not as a general `try/catch` that will automatically wrap your code and save you from errors completely. While you may be catching `NPE`, the fact that the code is going to throw when it attempts to `map` due to malformed data means it needs some extra love when it comes to syncing exceptions (via `syncThrowable`), *since the function passed to `map` itself is impure*.  This is not a bug, per se, and will result in the same behavior everywhere, across most (if not all) `Task` or `IO` types. 

However, you remove the need to use something like `syncThrowable` if you require that your functions be pure - that is, no using edge cases like `null`, such that your function is actually a function.

We'll come up with some in depth examples in a separate module so you (and others) can see what best practice + usability + use cases look like with respect to `IO`

**Comment by politrons** [comment]
@emilypi Thanks Emily I got that. Looking forward for those examples, I think they will be really useful.

**Comment by jmcardon** [comment]
At the risk of being difficult to understand, because this is pseudocode ("Response" doesn't actually exist) for a fake http server:
```scala
val fa: IO[Throwable, Response] = //.. Some business logic for my application that returns an httpResponse

fa.catchAll {
  case e: MyCustomError => IO.now(Response(e.getMessage, status = BadRequest))
  case e: Throwable => IO.syncThrowable(myLogger.info(e)("Caught unhandled error in application")) *> IO.now(Response(status = InternalServerError))
}
```

One thing I want to note is that while `e: Throwable` usually would match even errors you want to catch, `IO` only goes up to `NonFatal` errors (meaning not outofmemory errors or any errors which leave your VM in an undefined state), which makes this ok.

**Comment by jmcardon** [comment]
so in the above example, we're catching all errors that our application could throw, that are part of our application's logic.

If you messed up, and threw an exception in a pure function, this is _not_ caught by the handler, and you will not be saved. Thus, you can spot your error (programming error, that is)

**Comment by jdegoes** [comment]
`IO[E, A]` only handles "errors" in the functional programming sense — that is, values which encode typed error states. Just like `Either` handles "errors" as values constructed using `Left(_)`, so also `IO` handles "errors" as values constructed using `IO.fail(_)`. 

You would not expect `Left[String](null).map(_.toUpperCase)` to have magical behavior for exception throwing `f`, and similarly, you should not expect any methods of `IO` to have magical behavior for exception throwing, side-effecting code.

`catchSome` is the moral equivalent of the following function defined for `Either`:

```scala
def catchSome[A, B](e: Either[A, B])(pf: PartialFunction[A, Either[A, B]]): Either[A, B] = 
  e match {
    case Left(a) if pf.isDefinedAt(a) => pf(a)
    case _ => e
  }
```

As you can see, there is no magical behavior here, nor can there be—this method is polymorphic in `A` (and `B`), which gives you guarantees about its behavior under the Scalazzi subset of Scala that functional programming (and Scalaz) requires. It cannot know if `A` is `Throwable` nor behave differently in the case that it is (or is not).

If the documentation states, _such and such a function will catch an error_, it means an error modeled by a value (not an exception!) built from `IO.fail(_)`, and nothing more.

Now, sometimes you have to interface with legacy code—code which is not functional and which throws exceptions. In such case, what you want to do is translate an exception in the dysfunctional code into a value constructed using `IO.fail`. Naturally, you can do this manually, but it's such a common operation, it's built into the `IO` object as a series of helper methods:

 * **IO.syncThrowable** - Maps any `Throwable` into `IO.fail`.
 * **IO.syncException** - Maps any `Exception` into `IO.fail`.
 * **IO.syncCatch** - Maps a subset of `Throwable` into `IO.fail`.

These functions help you safely map impure code into its pure equivalent, but make no mistake: the `IO` monad is designed for purely functional programming (possibly interfacing with *non*-purely functional code as mentioned above), a paradigm in which only values are used to represent error states, not exceptions.

**Comment by politrons** [comment]
@jdegoes Thanks for the explanation, now everything it's perfectly clear. Unfortunately in the world that I living Pure FP is still an utopia, so I have to live with some OOP non pure  code that can cause those no controlled effects. So thanks for the sync operators, now that I know how to control unsafe code it will be very handy.

**Comment by emilypi** [comment]
@politrons we understand the struggle. Hopefully, the performance and productive benefits of working with `IO` will help carve out a more deterministic codebase for you. I have experience working in the same kind of environment, and recently won the struggle to do just that. It's been very rewarding 😄

**Comment by politrons** [comment]
I would love to work in a non defensive programing environment with Pure FP. It would reduce drastically my number of Unit test 😀

**Comment by jdegoes** [comment]
@politrons Please open this up again if you have any questions. :)
